Repository JECT-Study/Grass-Diary-Client, pull requests merged in 2024-09, with the labels that each got.

#184 💄 design: 공유페이지 UI 변경
  grass-diary/src/assets/svg/chevron_left.svg
  grass-diary/src/assets/svg/chevron_right.svg
  grass-diary/src/components/Button/BackButton.tsx
  grass-diary/src/components/Feed/Feed.tsx
  grass-diary/src/components/Feed/PopularFeed.tsx
  grass-diary/src/components/Layout/Footer.tsx
  grass-diary/src/components/Layout/Header.tsx
  grass-diary/src/pages/Main/BottomSection.tsx
  grass-diary/src/pages/Share/Share.tsx
  grass-diary/src/styles/GlobalStyle.ts
  grass-diary/src/types/feed.ts
Labels: ✨feature, 👩🏻‍💻frontend, 🪄refactor

#186 💄 design: 소개 페이지 desktop UI 변경
  grass-diary/public/assets/icons/button-solid-chevron-right.svg
  grass-diary/public/assets/icons/dialog-icon-btn-close.svg
  grass-diary/public/assets/icons/expand-more.svg
  grass-diary/public/assets/icons/logo.png
  grass-diary/public/assets/img/banner:record.svg
  grass-diary/public/assets/img/card:publicDiary.svg
  grass-diary/public/assets/img/googleLogin.png
  grass-diary/src/components/Divider.tsx
  grass-diary/src/components/index.ts
  grass-diary/src/constants/message.ts
  grass-diary/src/pages/Intro/Intro.tsx
  grass-diary/src/pages/Intro/LoginModal/LoginModal.tsx
  grass-diary/src/pages/Intro/introComponents.tsx
  grass-diary/src/pages/Intro/styles.ts
  grass-diary/src/styles/GlobalStyle.ts
  grass-diary/src/styles/Intro/IntroStyles.ts
  grass-diary/src/styles/Intro/LoginModal.ts
  grass-diary/src/styles/semantic.ts
  grass-diary/yarn.lock
Labels: 👩🏻‍💻frontend

#189 ✨feat: 모바일 UI 구현 및 모달, 토스트 컴포넌트 등 기능 추가
  grass-diary/package-lock.json
  grass-diary/package.json
  grass-diary/src/assets/svg/person_remove.svg
  grass-diary/src/components/Button/BackButton.tsx
  grass-diary/src/components/Button/Menus.tsx
  grass-diary/src/components/Comment/CommentDisplay.tsx
  grass-diary/src/components/Comment/Input.tsx
  grass-diary/src/components/Feed/Feed.tsx
  grass-diary/src/components/Feed/PopularFeed.tsx
  grass-diary/src/components/Layout/Footer.tsx
  grass-diary/src/components/Layout/Header.tsx
  grass-diary/src/components/Layout/Layout.tsx
  grass-diary/src/components/Layout/MenuBar.tsx
  grass-diary/src/components/Layout/Toast.tsx
  grass-diary/src/components/callout/Callout.tsx
  grass-diary/src/components/index.ts
  grass-diary/src/components/modal/CheckButton.tsx
  grass-diary/src/components/modal/CustomButton.tsx
  grass-diary/src/components/modal/Modal.tsx
  grass-diary/src/constants/message.ts
  grass-diary/src/hooks/api/useDeleteDiaryDetail.ts
  grass-diary/src/pages/CreateDiary/QuillEditor.tsx
  grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
  grass-diary/src/pages/DiaryDetail/NonExistentDiary.tsx
  grass-diary/src/pages/DiaryDetail/Setting.tsx
  grass-diary/src/pages/DiaryDetail/modal/ConfirmDeleteModal.tsx
  grass-diary/src/pages/DiaryDetail/modal/ImageModal.tsx
  grass-diary/src/pages/DiaryDetail/modal/UnmodifyModal.tsx
  grass-diary/src/pages/Share/Share.tsx
  grass-diary/src/router.tsx
  grass-diary/src/state/modal/ModalButtonStore.ts
  grass-diary/src/state/modal/ModalStore.ts
  grass-diary/src/state/modal/useModal.ts
  grass-diary/src/state/toast/ToastStore.ts
  grass-diary/src/state/toast/useToast.ts
  grass-diary/src/types/feed.ts
  grass-diary/src/types/modal.ts
Labels: ✨feature, 👩🏻‍💻frontend, 🪄refactor

#190 ✨ feat: 작성 페이지 임시저장 구현, UI 수정
  grass-diary/src/assets/svg/publish.svg
  grass-diary/src/assets/svg/publish_on.svg
  grass-diary/src/components/Button/Menu.tsx
  grass-diary/src/constants/emoji.ts
  grass-diary/src/constants/message.ts
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/CreateDiary/QuillEditor.tsx
  grass-diary/src/pages/Main/BottomSection.tsx
  grass-diary/src/pages/Main/Main.tsx
  grass-diary/src/pages/Main/MiddleSection.tsx
  grass-diary/src/pages/Main/TopSection.tsx
  grass-diary/src/styles/CreateDiary/CreateDiary.style.tsx
  grass-diary/src/styles/CreateDiary/QuillEditor.style.tsx
  grass-diary/src/styles/GlobalStyle.ts
  grass-diary/src/styles/Main/Banner.style.tsx
  grass-diary/src/styles/Main/BottomSection.style.tsx
  grass-diary/src/styles/Main/MiddleSection.style.tsx
  grass-diary/src/styles/Main/TopSection.style.tsx
  grass-diary/src/styles/typo.ts
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻frontend, 🪄refactor

#191 💄 design: 설정 페이지 desktop UI 변경
  grass-diary/public/assets/icons/button-outlined-chevron-right.svg
  grass-diary/public/assets/icons/checkTheme.svg
  grass-diary/public/assets/icons/darkTheme.svg
  grass-diary/public/assets/icons/lightTheme.svg
  grass-diary/public/assets/img/defaultAvatar.svg
  grass-diary/src/components/Profile/Profile.tsx
  grass-diary/src/constants/message.ts
  grass-diary/src/pages/Setting/Setting.tsx
  grass-diary/src/pages/Setting/Temporary.tsx
  grass-diary/src/pages/Setting/styles.ts
Labels: ✨feature, 👩🏻‍💻frontend

#197 ✨ feat: 작성 페이지 이미지 임시 저장 구현
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/CreateDiary/QuillEditor.tsx
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻frontend

#199 💄 design: 마이 페이지 desktop UI 변경
  grass-diary/public/assets/icons/icon-btn-chevron-left.svg
  grass-diary/public/assets/icons/icon-btn-chevron-right.svg
  grass-diary/public/assets/icons/icon-btn-first-page.svg
  grass-diary/public/assets/icons/icon-btn-last-page.svg
  grass-diary/public/assets/icons/more_horiz.svg
  grass-diary/public/assets/icons/pin.svg
  grass-diary/public/assets/icons/search.svg
  grass-diary/public/assets/icons/tag-tag.svg
  grass-diary/public/assets/img/banner_record.svg
  grass-diary/public/assets/img/card_publicDiary.svg
  grass-diary/src/components/Button/Menus.tsx
  grass-diary/src/components/Ellipsis.tsx
  grass-diary/src/components/Profile/MoodProfile.tsx
  grass-diary/src/pages/MyPage/Diary.tsx
  grass-diary/src/pages/MyPage/Grass.tsx
  grass-diary/src/pages/MyPage/MyPage.tsx
  grass-diary/src/pages/MyPage/myComponents.tsx
  grass-diary/src/pages/MyPage/style.ts
  grass-diary/src/types/diary.ts
Labels: ✨feature, 👩🏻‍💻frontend

#198 ♻ refactor: 수정페이지 UI 변경 및 스타일 컴포넌트 컨벤션 적용
  grass-diary/src/assets/svg/close.svg
  grass-diary/src/components/Button/BackButton.tsx
  grass-diary/src/components/Button/Menu.tsx
  grass-diary/src/components/Button/Menus.tsx
  grass-diary/src/components/Comment/CommentDisplay.tsx
  grass-diary/src/components/Comment/CommentSetting.tsx
  grass-diary/src/components/Comment/Comments.tsx
  grass-diary/src/components/Comment/Input.tsx
  grass-diary/src/components/Feed/Feed.tsx
  grass-diary/src/components/Feed/PopularFeed.tsx
  grass-diary/src/components/Layout/Footer.tsx
  grass-diary/src/components/Layout/Header.tsx
  grass-diary/src/components/Layout/Layout.tsx
  grass-diary/src/components/Layout/SnackBar.tsx
  grass-diary/src/components/Like/Like.tsx
  grass-diary/src/components/Like/NormalLike.tsx
  grass-diary/src/components/Notification/Callout.tsx
  grass-diary/src/components/Notification/CustomButton.tsx
  grass-diary/src/components/Notification/Modal.tsx
  grass-diary/src/components/Notification/Toast.tsx
  grass-diary/src/components/index.ts
  grass-diary/src/components/modal/Modal.tsx
  grass-diary/src/constants/message.ts
  grass-diary/src/hooks/api/useCreateDiary.ts
  grass-diary/src/hooks/api/usePatchDiary.ts
  grass-diary/src/hooks/api/usePostImage.ts
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/CreateDiary/QuillEditor.tsx
  grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
  grass-diary/src/pages/DiaryDetail/modal/ImageModal.tsx
  grass-diary/src/pages/EditDiary/EditDiary.tsx
  grass-diary/src/pages/Share/Share.tsx
  grass-diary/src/state/modal/ModalButtonStore.ts
  grass-diary/src/state/modal/ModalStore.ts
  grass-diary/src/state/modal/useModal.ts
  grass-diary/src/state/toast/SnackBarStore.ts
  grass-diary/src/state/toast/useSnackBar.ts
  grass-diary/src/styles/DiaryDetail/DiaryDetail.style.tsx
  grass-diary/src/styles/DiaryDetail/ImageModal.style.tsx
  grass-diary/src/styles/Share/Share.style.tsx
  grass-diary/src/styles/component/Button/BackButton.style.tsx
  grass-diary/src/styles/component/Button/Menu.style.tsx
  grass-diary/src/styles/component/Button/Menus.style.tsx
  grass-diary/src/styles/component/Comment/CommentDisplay.style.tsx
  grass-diary/src/styles/component/Comment/CommentSetting.style.tsx
  grass-diary/src/styles/component/Comment/Comments.style.tsx
  grass-diary/src/styles/component/Comment/Input.style.tsx
  grass-diary/src/styles/component/Feed/Feed.style.tsx
  grass-diary/src/styles/component/Feed/Popular.style.tsx
  grass-diary/src/styles/component/Layout/Footer.style.tsx
  grass-diary/src/styles/component/Layout/Header.style.tsx
  grass-diary/src/styles/component/Like/Like.style.tsx
  grass-diary/src/styles/component/Like/NormalLike.style.tsx
  grass-diary/src/styles/component/Notification/Callout.style.tsx
  grass-diary/src/styles/component/Notification/CustomButton.style.tsx
  grass-diary/src/styles/component/Notification/Modal.style.tsx
  grass-diary/src/styles/component/Notification/Toast.style.tsx
  grass-diary/src/types/diary.ts
  grass-diary/src/types/modal.ts
  grass-diary/yarn.lock
Labels: 👩🏻‍💻frontend, 🪄refactor

#202 💄 design: 작성 페이지 모바일 UI 구현
  grass-diary/src/components/modal/Modal.tsx
  grass-diary/src/constants/message.ts
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/Main/BottomSection.tsx
  grass-diary/src/pages/Main/TopSection.tsx
  grass-diary/src/state/modal/ModalButtonStore.ts
  grass-diary/src/state/modal/ModalStore.ts
  grass-diary/src/state/modal/useModal.ts
  grass-diary/src/styles/CreateDiary/CreateDiary.style.tsx
  grass-diary/src/styles/GlobalStyle.ts
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻frontend

#203 💄 design: 모바일 UI 구현 (소개 페이지, 마이 페이지, 설정 페이지)
  grass-diary/src/constants/api.ts
  grass-diary/src/constants/message.ts
  grass-diary/src/hooks/useIsMobile.ts
  grass-diary/src/pages/Intro/LoginModal/LoginModal.tsx
  grass-diary/src/pages/Intro/introComponents.tsx
  grass-diary/src/pages/MyPage/Diary.tsx
  grass-diary/src/pages/MyPage/Grass.tsx
  grass-diary/src/pages/MyPage/MyPage.tsx
  grass-diary/src/pages/MyPage/myComponents.tsx
  grass-diary/src/pages/Setting/Setting.tsx
  grass-diary/src/pages/Setting/Temporary.tsx
  grass-diary/src/styles/Intro/IntroStyles.ts
  grass-diary/src/styles/Intro/LoginModal.ts
  grass-diary/src/styles/MyPage/MyStyles.ts
  grass-diary/src/styles/Setting/SettingStyles.ts
Labels: ✨feature, 👩🏻‍💻frontend, 🪄refactor

#208 🐛 fix: 릴리즈 이후 버그 및 개선사항 적용
  grass-diary/src/components/Notification/Callout.tsx
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/styles/CreateDiary/CreateDiary.style.tsx
  grass-diary/src/styles/component/Notification/Callout.style.tsx
Labels: 🐛bug, 🪄refactor
