Repository JECT-Study/Grass-Diary-Client, pull requests merged in 2024-08, with the labels that each got.

#157 ♻ refactor: IProfile 타입 정리
  grass-diary/src/components/Profile/Profile.tsx
  grass-diary/src/pages/MyPage/Diary.tsx
  grass-diary/src/pages/Setting/Setting.tsx
  grass-diary/src/recoil/profile/useProfile.ts
  grass-diary/src/types/profile.ts
Labels: 👩🏻‍💻frontend, 🪄refactor

#159 ♻ refactor: EditDiary 페이지 Tanstack query 적용 및 localStroage의 lastWritingDate 사라짐 현상 해결
  grass-diary/src/components/Feed/PopularFeed.tsx
  grass-diary/src/hooks/api/useDiaryDetail.ts
  grass-diary/src/hooks/api/usePatchDiary.ts
  grass-diary/src/hooks/api/useTodayDate.ts
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
  grass-diary/src/pages/DiaryDetail/Setting.tsx
  grass-diary/src/pages/EditDiary/EditDiary.tsx
  grass-diary/src/pages/Main/TopSection.tsx
  grass-diary/src/types/diary.ts
  grass-diary/src/types/today.ts
Labels: ✨feature, 👩🏻‍💻frontend, 🪄refactor

#160 🔧 chore: zustand 라이브러리 설치
  grass-diary/package-lock.json
  grass-diary/package.json
  grass-diary/src/components/Header.tsx
  grass-diary/src/main.tsx
  grass-diary/src/pages/MyPage/myComponents.tsx
  grass-diary/src/pages/Setting/Setting.tsx
  grass-diary/src/pages/index.ts
  grass-diary/src/router.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#162 ♻ refactor: 작성 페이지 리팩토링, Tanstack Query 적용
  grass-diary/src/hooks/api/useCreateDiary.ts
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/Main/MiddleSection.tsx
  grass-diary/src/pages/Main/TopSection.tsx
  grass-diary/src/types/grass.ts
Labels: ✔︎pull requests, 👩🏻‍💻frontend, 🪄refactor

#163 :recycle: refactor: useAuth hook recoil에서 zustand로 변경
  grass-diary/src/components/Header.tsx
  grass-diary/src/components/Like/Like.tsx
  grass-diary/src/components/Profile/Profile.tsx
  grass-diary/src/components/ProtectedRoute.tsx
  grass-diary/src/hooks/useLogout.ts
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
  grass-diary/src/pages/Intro/introComponents.tsx
  grass-diary/src/pages/Main/Main.tsx
  grass-diary/src/pages/Main/MiddleSection.tsx
  grass-diary/src/pages/MyPage/Diary.tsx
  grass-diary/src/pages/MyPage/Grass.tsx
  grass-diary/src/pages/MyPage/myComponents.tsx
  grass-diary/src/pages/Setting/Setting.tsx
  grass-diary/src/recoil/auth/authSelector.ts
  grass-diary/src/recoil/auth/authState.ts
  grass-diary/src/recoil/auth/useAuth.ts
  grass-diary/src/services/index.ts
  grass-diary/src/state/auth/authStore.ts
  grass-diary/src/state/auth/authUtils.ts
  grass-diary/src/state/auth/useAuth.ts
  grass-diary/src/state/profile/profileSelector.ts
  grass-diary/src/state/profile/profileState.ts
  grass-diary/src/state/profile/useProfile.ts
  grass-diary/src/state/user/useUser.ts
  grass-diary/src/state/user/userState.ts
  grass-diary/tsconfig.paths.json
  grass-diary/vite.config.ts
Labels: 🐛bug, 👩🏻‍💻frontend, 🪄refactor

#168 ✨ feat: zustand 적용
  grass-diary/src/components/Header.tsx
  grass-diary/src/components/Like/Like.tsx
  grass-diary/src/components/Profile/Profile.tsx
  grass-diary/src/components/ProtectedRoute.tsx
  grass-diary/src/hooks/useLogout.ts
  grass-diary/src/main.tsx
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
  grass-diary/src/pages/Main/Main.tsx
  grass-diary/src/pages/Main/MiddleSection.tsx
  grass-diary/src/pages/MyPage/Diary.tsx
  grass-diary/src/pages/MyPage/Grass.tsx
  grass-diary/src/pages/MyPage/myComponents.tsx
  grass-diary/src/pages/Setting/Setting.tsx
  grass-diary/src/state/auth/authStore.ts
  grass-diary/src/state/auth/authUtils.ts
  grass-diary/src/state/auth/useAuth.ts
  grass-diary/src/state/profile/ProfileStore.ts
  grass-diary/src/state/profile/profileSelector.ts
  grass-diary/src/state/profile/profileState.ts
  grass-diary/src/state/profile/useProfile.ts
  grass-diary/src/state/user/UserStore.ts
  grass-diary/src/state/user/useUser.ts
  grass-diary/src/state/user/userState.ts
  grass-diary/src/types/profile.ts
  grass-diary/vite.config.ts
Labels: ✔︎pull requests, ✨feature, 👩🏻‍💻frontend, 🪄refactor

#169 ✨feat: 수정된 일기 api 적용
  grass-diary/src/constants/api.ts
  grass-diary/src/hooks/api/useCreateDiary.ts
  grass-diary/src/hooks/api/usePatchDiary.ts
  grass-diary/src/hooks/api/usePostImage.ts
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/CreateDiary/QuillEditor.tsx
  grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
  grass-diary/src/pages/EditDiary/EditDiary.tsx
  grass-diary/src/types/diary.ts
Labels: ✨feature, 👩🏻‍💻frontend

#164 💄design: NavBar 컴포넌트 디자인 변경
  grass-diary/.gitignore
  grass-diary/package-lock.json
  grass-diary/package.json
  grass-diary/src/assets/image/sampleLogo.png
  grass-diary/src/assets/svg/arrow_drop_down.svg
  grass-diary/src/assets/svg/avatarBg.svg
  grass-diary/src/assets/svg/grass.svg
  grass-diary/src/assets/svg/logo.svg
  grass-diary/src/assets/svg/logout.svg
  grass-diary/src/assets/svg/person.svg
  grass-diary/src/assets/svg/person_remove.svg
  grass-diary/src/assets/svg/settings.svg
  grass-diary/src/assets/testImg.avif
  grass-diary/src/components/Button/ButtonWrapper.tsx
  grass-diary/src/components/Button/Menu.tsx
  grass-diary/src/components/Button/Menus.tsx
  grass-diary/src/components/Header.tsx
  grass-diary/src/components/Interactions/Interaction1.tsx
  grass-diary/src/components/Interactions/Interaction2.tsx
  grass-diary/src/components/Interactions/Interaction3.tsx
  grass-diary/src/components/Interactions/Interaction4.tsx
  grass-diary/src/components/NavBar/Header.tsx
  grass-diary/src/components/NavBar/MenuBar.tsx
  grass-diary/src/components/index.ts
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/styles/GlobalStyle.ts
  grass-diary/src/styles/semantic.ts
  grass-diary/src/types/Interaction.ts
  grass-diary/src/types/custom.d.ts
  grass-diary/tsconfig.json
  grass-diary/tsconfig.paths.json
  grass-diary/vite.config.ts
Labels: ✨feature, 👩🏻‍💻frontend

#181 ♻ refactor: 전역 컴포넌트 분리 및 가로스크롤 제거
  grass-diary/src/components/Layout/Footer.tsx
  grass-diary/src/components/Layout/Header.tsx
  grass-diary/src/components/Layout/Layout.tsx
  grass-diary/src/components/Layout/MenuBar.tsx
  grass-diary/src/components/Layout/Toast.tsx
  grass-diary/src/components/ProtectedRoute.tsx
  grass-diary/src/components/index.ts
  grass-diary/src/main.tsx
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
  grass-diary/src/pages/DiaryDetail/NonExistentDiary.tsx
  grass-diary/src/pages/EditDiary/EditDiary.tsx
  grass-diary/src/pages/Intro/Intro.tsx
  grass-diary/src/pages/Main/Main.tsx
  grass-diary/src/pages/MyPage/MyPage.tsx
  grass-diary/src/pages/RewardPage/RewardPage.tsx
  grass-diary/src/pages/Setting/Setting.tsx
  grass-diary/src/pages/Share/Share.tsx
  grass-diary/src/router.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#182 ✨ feat: INTERACTION 상수 생성
  grass-diary/src/components/Button/BackButton.tsx
  grass-diary/src/components/Button/Menu.tsx
  grass-diary/src/components/Button/Menus.tsx
  grass-diary/src/components/Comment/CommentSetting.tsx
  grass-diary/src/components/Comment/Comments.tsx
  grass-diary/src/components/Comment/Input.tsx
  grass-diary/src/components/Interactions/Interaction1.tsx
  grass-diary/src/components/Interactions/Interaction2.tsx
  grass-diary/src/components/Interactions/Interaction3.tsx
  grass-diary/src/components/Interactions/Interaction4.tsx
  grass-diary/src/components/Layout/Header.tsx
  grass-diary/src/components/Layout/MenuBar.tsx
  grass-diary/src/components/Like/Like.tsx
  grass-diary/src/components/index.ts
  grass-diary/src/components/modal/CheckButton.tsx
  grass-diary/src/components/modal/CustomButton.tsx
  grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
  grass-diary/src/pages/DiaryDetail/Setting.tsx
  grass-diary/src/pages/DiaryDetail/modal/ConfirmDeleteModal.tsx
  grass-diary/src/pages/DiaryDetail/modal/UnmodifyModal.tsx
  grass-diary/src/styles/interaction.ts
  grass-diary/src/types/Interaction.ts
  grass-diary/src/types/diary.ts
Labels: ✨feature, 👩🏻‍💻frontend
