Repository JECT-Study/Grass-Diary-Client, pull requests merged in 2024-05, with the labels that each got.

#99 ♻️ refactor: TypeScript 적용
  .DS_Store
  grass-diary/.gitignore
  grass-diary/src/components/Button/BackButton.tsx
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/CreateDiary/QuillEditor.tsx
  grass-diary/src/pages/Main/Main.tsx
Labels: ⚙️chore, 👩🏻‍💻frontend, 🪄refactor

#102 :recycle: refactor: TypeScript 적용
  grass-diary/src/pages/Main/AnimateReward.tsx
Labels: ⚙️chore, 👩🏻‍💻frontend, 🪄refactor

#104 ♻️ refactor: 메인페이지 / 작성페이지 API 변경 , 파비콘 추가
  grass-diary/index.html
  grass-diary/src/assets/icon/favicon.ico
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/CreateDiary/QuillEditor.tsx
  grass-diary/src/pages/Main/Main.tsx
Labels: 👩🏻‍💻frontend, 🧹cleanup, 🪄refactor

#112 :hammer: fix: 마이 페이지 연간 잔디 오류 수정
  grass-diary/src/pages/MyPage/Grass.tsx
Labels: 🐛bug, 👩🏻‍💻frontend

#110 ♻️ refactor: Tanstack Query 적용 (메인 페이지)
  grass-diary/package-lock.json
  grass-diary/package.json
  grass-diary/src/pages/Main/BottomSection.tsx
  grass-diary/src/pages/Main/Main.tsx
  grass-diary/src/pages/Main/MiddleSection.tsx
  grass-diary/src/pages/Main/TopSection.tsx
Labels: 👩🏻‍💻frontend, 🪄refactor

#108 ✨ feat: 삭제 후 페이지 이동 경로 수정
  grass-diary/src/hooks/useDiaryDetail.ts
  grass-diary/src/pages/Diary/Diary.tsx
  grass-diary/src/pages/Diary/NonExistentDiary.tsx
  grass-diary/src/pages/Diary/modal/CompleteDeleteModal.tsx
Labels: ✨feature

#118 🐛bug: PopularFeed 피드 없을 때 문구 뜨지 않는 버그 수정
  grass-diary/src/components/Feed/PopularFeed.tsx
Labels: 🐛bug, 👩🏻‍💻frontend

#121 :hammer: fix: 소개 페이지 로그인 모달 위치 수정
  grass-diary/src/pages/Intro/LoginModal/LoginModal.tsx
  grass-diary/src/pages/Intro/introComponents.tsx
  grass-diary/src/types/modal.ts
Labels: 🐛bug, 👩🏻‍💻frontend
