Repository JECT-Study/Grass-Diary-Client, pull requests merged in 2024-10, with the labels that each got.

#214 ✨ feat: 리워드 내역 페이지 UI 구현
  grass-diary/public/assets/img/mainCharacter.png
  grass-diary/src/assets/icon/grass.png
  grass-diary/src/assets/icon/grassDiary.png
  grass-diary/src/assets/icon/mainCharacter.png
  grass-diary/src/assets/icon/subCharacter.png
  grass-diary/src/assets/image/pot.png
  grass-diary/src/constants/api.ts
  grass-diary/src/hooks/api/useRewardHistory.ts
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/RewardPage/RewardPage.tsx
  grass-diary/src/styles/CreateDiary/CreateDiary.style.ts
  grass-diary/src/styles/CreateDiary/QuillEditor.style.ts
  grass-diary/src/styles/Main/BottomSection.style.ts
  grass-diary/src/styles/Main/MiddleSection.style.ts
  grass-diary/src/styles/Main/Spacer.style.ts
  grass-diary/src/styles/Main/TopSection.style.ts
  grass-diary/src/styles/RewardPage/RewardPage.style.ts
  grass-diary/src/types/reward.ts
Labels: ✨feature, 👩🏻‍💻frontend

#215 ✨feat: 에러 처리 수정
  grass-diary/src/assets/svg/error_outline.svg
  grass-diary/src/components/Comment/CommentDisplay.tsx
  grass-diary/src/components/Comment/CommentSetting.tsx
  grass-diary/src/components/Comment/Input.tsx
  grass-diary/src/components/Feed/Feed.tsx
  grass-diary/src/components/Layout/Header.tsx
  grass-diary/src/components/Like/Like.tsx
  grass-diary/src/constants/message.ts
  grass-diary/src/hooks/api/comment/useDeleteComment.ts
  grass-diary/src/hooks/api/comment/usePatchComment.ts
  grass-diary/src/hooks/api/comment/usePostComment.ts
  grass-diary/src/hooks/api/useCountLike.ts
  grass-diary/src/hooks/api/useCreateDiary.ts
  grass-diary/src/hooks/api/useDeleteDiaryDetail.ts
  grass-diary/src/hooks/api/useGrassRecord.ts
  grass-diary/src/hooks/api/usePatchDiary.ts
  grass-diary/src/hooks/api/usePostImage.ts
  grass-diary/src/hooks/api/useReward.ts
  grass-diary/src/hooks/useApiError.ts
  grass-diary/src/hooks/useNetwork.ts
  grass-diary/src/main.tsx
  grass-diary/src/pages/CreateDiary/CreateDiary.tsx
  grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
  grass-diary/src/pages/DiaryDetail/Setting.tsx
  grass-diary/src/pages/Error/ErrorPage.tsx
  grass-diary/src/pages/Error/NotFoundPage.tsx
  grass-diary/src/pages/Main/TopSection.tsx
  grass-diary/src/pages/MyPage/Diary.tsx
  grass-diary/src/pages/MyPage/Grass.tsx
  grass-diary/src/pages/Setting/Setting.tsx
  grass-diary/src/pages/index.ts
  grass-diary/src/router.tsx
  grass-diary/src/state/profile/useProfile.ts
  grass-diary/src/state/toast/useToast.ts
  grass-diary/src/state/user/useUser.ts
  grass-diary/src/styles/Error/NotFoundPage.style.tsx
  grass-diary/src/styles/component/Notification/Toast.style.tsx
Labels: ✨feature, 👩🏻‍💻frontend

#217 ✨feat: 테마 페이지 구현
  grass-diary/src/assets/svg/navigate_next.svg
  grass-diary/src/constants/api.ts
  grass-diary/src/hooks/api/ useThemeList.ts
  grass-diary/src/hooks/api/useTheme.ts
  grass-diary/src/hooks/api/useThemeSetting.ts
  grass-diary/src/pages/Main/BottomSection.tsx
  grass-diary/src/pages/RewardPage/RewardPage.tsx
  grass-diary/src/pages/Setting/Setting.tsx
  grass-diary/src/pages/ThemePage/ThemeSettingPage.tsx
  grass-diary/src/pages/ThemePage/ThemeStorePage.tsx
  grass-diary/src/pages/index.ts
  grass-diary/src/router.tsx
  grass-diary/src/styles/Main/BottomSection.style.ts
  grass-diary/src/styles/RewardPage/RewardPage.style.ts
  grass-diary/src/styles/ThemePage/ThemePage.style.ts
Labels: ✨feature, 👩🏻‍💻frontend

#218 🔨 fix: 릴리즈 이후 버그 및 기능 수정
  grass-diary/src/components/Profile/MoodProfile.tsx
  grass-diary/src/constants/api.ts
  grass-diary/src/constants/message.ts
  grass-diary/src/pages/Setting/Setting.tsx
  grass-diary/src/pages/Withdraw/Withdraw.tsx
  grass-diary/src/router.tsx
  grass-diary/src/state/profile/ProfileStore.ts
  grass-diary/src/state/profile/useProfile.ts
  grass-diary/src/styles/Setting/SettingStyles.ts
  grass-diary/src/styles/Withdraw/Withdraw.style.tsx
  grass-diary/src/types/profile.ts
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#228 ✨feat: 날짜와 상관없이 공개/비공개 설정 기능 구현
  grass-diary/src/assets/svg/lock_black.svg
  grass-diary/src/assets/svg/lock_open_black.svg
  grass-diary/src/constants/api.ts
  grass-diary/src/constants/message.ts
  grass-diary/src/hooks/api/usePatchVisibility.ts
  grass-diary/src/pages/DiaryDetail/DiaryDetail.tsx
  grass-diary/src/pages/DiaryDetail/Setting.tsx
  grass-diary/src/pages/RewardPage/RewardPage.tsx
  grass-diary/src/pages/ThemePage/ThemeStorePage.tsx
  grass-diary/src/services/index.ts
  grass-diary/src/styles/component/Notification/SnackBar.style.tsx
Labels: ✨feature, 🐛bug, 👩🏻‍💻frontend

#229 🔨 fix: 로그인 만료 로직 변경
  grass-diary/package-lock.json
  grass-diary/package.json
  grass-diary/src/components/Layout/Header.tsx
  grass-diary/src/hooks/useLogout.ts
  grass-diary/src/state/auth/authStore.ts
  grass-diary/src/state/auth/useAuth.ts
  grass-diary/src/state/auth/useExpDate.ts
  grass-diary/src/state/modal/useModal.ts
  grass-diary/src/state/user/useUser.ts
Labels: ✨feature, 👩🏻‍💻frontend, 🪄refactor
